parameters:
  registry_name: ''
  deps_label: ''
jobs:
- job: PublishArtifactsJob # publish helm charts
  timeoutInMinutes: 30  
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Chart to Artifact Staging Directory'
    inputs:
      Contents: '**/presidio/charts/**'
      TargetFolder: charts
      CleanTargetFolder: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dropchart'
    inputs:
      PathtoPublish: charts
      ArtifactName: dropchart  

- job: PushImagesJob # push images to registry 
  - bash: | # push with build-id label - all branches
      make DOCKER_REGISTRY=$REGISTRY_NAME PRESIDIO_LABEL=$(Build.BuildID) docker-push
    env:
      REGISTRY_NAME: ${{ parameters.registry_name }}
    displayName: 'Push Docker Images - BuildId label'      

  - bash: | # push with latest label - master branch
      make DOCKER_REGISTRY=$REGISTRY_NAME PRESIDIO_LABEL=$(Build.BuildID) PRESIDIO_DEPS_LABEL=$(DEPS_LABEL) docker-push-latest-deps
      make DOCKER_REGISTRY=$REGISTRY_NAME PRESIDIO_LABEL=$(Build.BuildId) RELEASE_VERSION='$(RELEASE_NAME)' docker-push-release                    
    env:
      REGISTRY_NAME: ${{ parameters.registry_name }}
      DEPS_LABEL: ${{ parameters.deps_label }}
    displayName: 'Push Docker Images - Master Branch'    
    condition: eq(variables['Build.SourceBranchName'], 'master')

  - bash: | # push with latest-dev label - development branch
      make DOCKER_REGISTRY=$REGISTRY_NAME PRESIDIO_LABEL=$(Build.BuildID) PRESIDIO_DEPS_LABEL=$(DEPS_LABEL) docker-push-latest-dev-deps
      make DOCKER_REGISTRY=$REGISTRY_NAME PRESIDIO_LABEL=$(Build.BuildId) docker-push-latest-dev      
    env:
      REGISTRY_NAME: ${{ parameters.registry_name }}
      DEPS_LABEL: ${{ parameters.deps_label }}
    displayName: 'Push Docker Images - Development Branch'    
    condition:  eq(variables['Build.SourceBranchName'], 'development')

  - bash: | # push with branch-name label - feature branch
      make DOCKER_REGISTRY=$REGISTRY_NAME PRESIDIO_LABEL=$(Build.BuildID) PRESIDIO_DEPS_LABEL=$(DEPS_LABEL) PRESIDIO_BRANCH_LABEL=$(Build.SourceBranchName) docker-push-latest-branch-deps
      make DOCKER_REGISTRY=$REGISTRY_NAME PRESIDIO_LABEL=$(Build.BuildID) PRESIDIO_DEPS_LABEL=$(DEPS_LABEL) PRESIDIO_BRANCH_LABEL=$(Build.SourceBranchName) push-latest-branch
    env:
      REGISTRY_NAME: ${{ parameters.registry_name }}
      DEPS_LABEL: ${{ parameters.deps_label }}
    displayName: 'Push Docker Images - Feature Branch'    
    condition: and(ne(variables['Build.SourceBranchName'], 'development'), ne(variables['Build.SourceBranchName'], 'master'))