definitions:
  AnalyzeRequest:
    description: AnalyzeRequest represents the request to the analyze service via
      GRPC
    properties:
      analyzeTemplate:
        $ref: '#/definitions/AnalyzeTemplate'
      text:
        description: The text to analyze
        type: string
        x-go-name: Text
    type: object
    x-go-package: github.com/Microsoft/presidio-genproto/golang
  AnalyzeResult:
    description: AnalyzeResult represents the Analyze service findings
    properties:
      field:
        $ref: '#/definitions/FieldTypes'
      location:
        $ref: '#/definitions/Location'
      score:
        description: The score of the result
        format: float
        type: number
        x-go-name: Score
      text:
        description: The sensitive text result
        type: string
        x-go-name: Text
    type: object
    x-go-package: github.com/Microsoft/presidio-genproto/golang
  AnalyzeTemplate:
    properties:
      allFields:
        description: Optional flag to request all existing fields. if true, "fields"
          must be empty.
        type: boolean
        x-go-name: AllFields
      createTime:
        description: Template Creation date
        type: string
        x-go-name: CreateTime
      description:
        description: Template description
        type: string
        x-go-name: Description
      fields:
        description: Array of the fields to analyze
        items:
          $ref: '#/definitions/FieldTypes'
        type: array
        x-go-name: Fields
      language:
        description: Language code, in ISO-639 format, https://en.wikipedia.org/wiki/ISO_639-1
        type: string
        x-go-name: Language
      modifiedTime:
        description: Template modification date
        type: string
        x-go-name: ModifiedTime
      resultsScoreThreshold:
        description: Threshold to filter results based on their score
        format: float
        type: number
        x-go-name: ResultsScoreThreshold
    title: AnalyzeTemplate represents the template definition of the Analyze service-
      for analyzing sensitive text.
    type: object
    x-go-package: github.com/Microsoft/presidio-genproto/golang
  FieldTypes:
    description: FieldType strucy
    properties:
      minScore:
        description: The minScore will filter results which has lower certainty than
          the provided value.
        type: string
        x-go-name: MinScore
      name:
        description: Field type name
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/Microsoft/presidio-genproto/golang
  Location:
    description: The location in the text of the finding
    properties:
      end:
        description: The location end
        format: int32
        type: integer
        x-go-name: End
      length:
        description: The location length
        format: int32
        type: integer
        x-go-name: Length
      start:
        description: The location start
        format: int32
        type: integer
        x-go-name: Start
    type: object
    x-go-package: github.com/Microsoft/presidio-genproto/golang
  Pattern:
    description: |-
      Pattern represents one regex (pattern) that is able to detect a certain
      entity and how confident the result is
    properties:
      name:
        description: The name of the pattern, unique
        type: string
        x-go-name: Name
      regex:
        description: The Regex used by this recognizer
        type: string
        x-go-name: Regex
      score:
        description: The confidence of the result
        format: float
        type: number
        x-go-name: Score
    type: object
    x-go-package: github.com/Microsoft/presidio-genproto/golang
  PatternRecognizer:
    description: |-
      PatternRecognizer represents a recognizer which has the ability to detect
      entities using one or more Patterns
    properties:
      blacklist:
        description: |-
          A list of words that are considered PII and should always be detected
          e.g. ["Mr", "Mrs", "account"]
        items:
          type: string
        type: array
        x-go-name: Blacklist
      contextPhrases:
        description: |-
          A list of strings that if found in the surroundings of the entity, increase the score of the result
          e.g. ["name", "address", ]
        items:
          type: string
        type: array
        x-go-name: ContextPhrases
      entity:
        description: The entity name which this recognizer can detect
        type: string
        x-go-name: Entity
      language:
        description: The supported language code, in ISO-639 format, https://en.wikipedia.org/wiki/ISO_639-1
        type: string
        x-go-name: Language
      name:
        description: The name of the recognizer, unique
        type: string
        x-go-name: Name
      patterns:
        description: List of supported patterns by this recognizer
        items:
          $ref: '#/definitions/Pattern'
        type: array
        x-go-name: Patterns
    type: object
    x-go-package: github.com/Microsoft/presidio-genproto/golang
  RecognizersGetResponse:
    description: RecognizersGetResponse represents a response to a get request
    properties:
      recognizers:
        description: An array of recognizers
        items:
          $ref: '#/definitions/PatternRecognizer'
        type: array
        x-go-name: Recognizers
    type: object
    x-go-package: github.com/Microsoft/presidio-genproto/golang
paths:
  /analyzer/recognizers/{id}:
    get:
      description: Get an existing recognizer
      operationId: getRecognizer
      parameters:
      - description: Recognizer name
        in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      responses:
        "200":
          $ref: '#/responses/recognizersGetResponse'
      tags:
      - analyzer
  /projects/{projectId}/analyze:
    post:
      description: Analyze text
      operationId: analyzeRequest
      parameters:
      - description: Project ID
        format: int64
        in: path
        name: projectId
        required: true
        type: integer
        x-go-name: ProjectId
      - description: The request body
        in: body
        name: Body
        schema:
          $ref: '#/definitions/AnalyzeRequest'
      responses:
        "200":
          $ref: '#/responses/analyzeResponse'
      tags:
      - analyze
responses:
  analyzeResponse:
    description: A response includes a list of recognized fields in the text to be
      anonymized.
    schema:
      items:
        $ref: '#/definitions/AnalyzeResult'
      type: array
  recognizersGetResponse:
    description: A response includes a list of recognized fields in the text to be
      anonymized.
    schema:
      $ref: '#/definitions/RecognizersGetResponse'
swagger: "2.0"
