variables:
  GOBIN: '$(GOPATH)/bin'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  MODULEPATH: '$(GOPATH)/src/github.com/$(build.repository.name)'
  GOROOT: '/usr/local/go1.11's

trigger: # CI triggers	
  batch: false 
  branches:
      include: 
      - master	
  paths:
    exclude: 
      - Dockerfile.golang.deps	
      - Gopkg.lock	
      - Gopkg.toml	
      - Dockerfile.python.deps
      - presidio-analyzer/Pipfile
      - presidio-analyzer/Pipfile.lock	
      - '*.md'
pr: # PR triggers	
  branches:
      include: 
      - development	
  paths:
    exclude: 
      - Dockerfile.golang.deps	
      - Gopkg.lock	
      - Gopkg.toml	
      - Dockerfile.python.deps	
      - presidio-analyzer/Pipfile
      - presidio-analyzer/Pipfile.lock
      - '*.md'
stages:
  - template: templates/build-test-publish.yaml
    parameters:
      build_deps: false
      registry_service_principal: $(REGISTRY)
      registry_name: $(REGISTRY_NAME)
      artifact_feed: presidio