variables:
  GOBIN: '$(GOPATH)/bin'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  MODULEPATH: '$(GOPATH)/src/github.com/$(build.repository.name)'
  GOROOT: '/usr/local/go1.11'
  PYTHON.VERSION: '3.7'

trigger: # CI triggers	
  batch: false 
  branches:
      include: 
      - master	
  paths:
    exclude: 
      - '*.md'
pr: # PR triggers	
  branches:
      include: 
      - development	
  paths:
    exclude: 
      - '*.md'
stages:
  - template: templates/build-test-publish.yaml
    parameters:
      registry_service_principal: $(REGISTRY)
      registry_name: $(REGISTRY_NAME)
      artifact_feed: presidio
      pypi_extra_index_url: https://pkgs.dev.azure.com/csedevil/_packaging/presidio/pypi/simple/

